export const contributors = [
	{
		id: 0,
		user: "aforcita",
		img: "/contributors/aforcita.svg",
		github_url: "https://github.com/afordigital",
	},
	{
		id: 1,
		user: "Alberto S",
		img: "/contributors/alberto.svg",
		github_url: "https://github.com/afordigital",
	},
	{
		id: 2,
		title: "Felix Icaza",
		img: "/contributors/felixicaza.svg",
		github_url: "https://github.com/felixicaza",
	},
	{
		id: 3,
		title: "Freilyn Bernabe",
		img: "/contributors/berna.svg",
		github_url: "https://github.com/bernabedev",
	},
	{
		id: 4,
		title: "Cristina Díaz",
		img: "/contributors/krepsi.svg",
		github_url: "https://github.com/Krepssier",
	},
	{
		id: 5,
		title: "Jhon",
		img: "/contributors/jhon.svg",
		github_url: "https://github.com/vyers",
	},
	{
		id: 6,
		title: "Bulbito",
		img: "/contributors/aforcita.svg",
		github_url: "https://github.com/Ch1py7",
	},
	{
		id: 7,
		title: "Mateo Morales",
		img: "/contributors/vimofama.svg",
		github_url: "https://github.com/vimofama",
	},
	{
		id: 8,
		title: "Leonardo Salazar",
		img: "/contributors/leonardo.svg",
		github_url: "https://github.com/developerleonardo",
	},
	{
		id: 9,
		title: "Nicole",
		img: "/contributors/nicole.svg",
		github_url: "https://github.com/LauraNicole449",
	},
	{
		id: 10,
		title: "Alexis",
		img: "/contributors/alexis.svg",
		github_url: "https://github.com/gvrciary",
	},
	{
		id: 11,
		title: "Bauti",
		img: "/contributors/bauti.svg",
		github_url: "https://github.com/Bauti567",
	},
	{
		id: 12,
		title: "Tovir",
		img: "/contributors/tovir.svg",
		github_url: "https://github.com/vadegad0",
	},
	{
		id: 13,
		title: "kuro",
		img: "/contributors/kuro.svg",
		github_url: "https://github.com/ikurotime",
	},
	{
		id: 14,
		title: "jarrison",
		img: "/contributors/jarrison.svg",
		github_url: "https://github.com/jarrisondev",
	},
	{
		id: 15,
		title: "vladiantio",
		img: "/contributors/vladiantio.svg",
		github_url: "https://github.com/vladiantio",
	},
	{
		id: 16,
		title: "erian",
		img: "/contributors/erian.svg",
		github_url: "https://github.com/eriandev",
	},
];
